export const GET_USER = 'GET_USER / INSTAUSER'
export const GET_PICTURES = 'GET_PICTURES / INSTAUSER'
export const GET_COMMENT = 'GET_COMMENT / INSTAUSER'
export const CREATE_COMMENT = 'CREATE_COMMENT / INSTAUSER'